### PR TITLE
assessments, cleanup, fixes

### PR DESCRIPTION
**Pull request by ksimuk**

### CODE REVIEW

**Comment by ghost** [comment]
2 files missing
missingfiles_2
missingfile

**Comment by ksimuk** [comment]
this is coding with java, why js files?

**Comment by ghost** [comment]
Didn't notice that and looking it would see that in the current published unit they are also js files in error and no one has noticed or commented but even so there aren't any /java files in these folders either :)

**Comment by ksimuk** [comment]
looks like someone just copy pasted the content, this section is very stange, because java doesn't have functions

**Comment by ksimuk** [comment]
code examples are fixed

**Comment by ghost** [comment]
:+1:

**Pull request merged**
